### ISSUE TITLE
Transparency and loads of other stuff not working

### ISSUE THREAD

**Issue by Quick-Lightning** [witalihirsch/QTWin11#1]
So I cloned the repos and `python main.py` -ed, but uhh it's not working
I get this error in terminal- QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 255, 255, 255, 20'

And the transparency and other issues that I'm getting can be best explained by an image.
![image](https://user-images.githubusercontent.com/93387928/167286725-e5f55b4b-01ef-47d1-9a2e-69bd5cbdd149.png)

Also, the background becomes white in the Alt-Tab preview menu
![image](https://user-images.githubusercontent.com/93387928/167286753-48b9c54f-7eb5-49dd-89d7-e204627a47be.png)

**Comment by Quick-Lightning** [comment]
I just realised that the transparency issues might be to do with the fact that I'm on Windows 10 v19044 and win32mica is for Windows 11

**Comment by witalihirsch** [comment]
> I just realised that the transparency issues might be to do with the fact that I'm on Windows 10 v19044 and win32mica is for Windows 11

You use Windows 10 or Windows 11?

**Comment by witalihirsch** [comment]
> > You use Windows 10 or Windows 11?
> 
> Windows 10 v19044.1862

Mica material is only available on Windows 11. See requirements.
