### ISSUE TITLE
Patching preexisting software to use this theme

### ISSUE THREAD

**Issue by skinatro** [witalihirsch/QTWin11#5]
Hello is there anyway we can use this repo to patch pre existing software on windows like it's done on linux?
You can use tools like `qt5ct` on linux to make linux software follow a homogenous theme.
Can this be done on windows? To my knowledge the Qt Stylesheets are just `.dll` files on windows

**Comment by witalihirsch** [comment]
To be honest, I can't answer your question, but I don't think this can be done on windows. this stylesheet can be used for apps written in python or c++, but written specifically with this stylesheet

**Comment by skinatro** [comment]
oh, thanks for lot for the reply.
