### ISSUE TITLE
KDE Plasma?

### ISSUE THREAD

**Issue by lollilol** [witalihirsch/QTWin11#6]
Can i use this somehow in KDE Plasma on Arch? Or does this project fulfill a completely different purpose?
![image](https://github.com/witalihirsch/QTWin11/assets/38194372/3b327a5d-218d-400f-bfd8-bf295a85e631)

**Comment by Advik-B** [comment]
Its in the name *Qt***Win11** It specially uses WINAPI to achieve this blurring, hence the reason its not cross platform, hence it's name.
